### ISSUE TITLE
Add Verbiage on Supply Entry Link Formatting

### ISSUE THREAD

**Issue by snchildress** [lucidhq/developer-documentation#117]
We should have verbiage under the POST Create a Link call and on the Supply Integration Guide under Phase II: 3. Create a Link about how to format entry links with a link to a supplier-specific list of available variables. Because creating and formatting entry links is part of the development process, it should be explained with the rest of our development documentation. It also doesn't belong on the support page because the current information on supplier link formatting is API-specific as Pulley has its own formatting.

**Comment by brenankeller** [comment]
I believe PR #121 resolves this issue.
