### ISSUE TITLE
Fix Broken Link on GET Show Quotas

### ISSUE THREAD

**Issue by snchildress** [lucidhq/developer-documentation#120]
In the aside under GET Show Quotas, there is a broken link -- markdown cannot be used within the aside. Need to update markdown to full HTML link tag.

Additionally, under GET Show a Survey, there is a reference to the NumberOfRespondents property not having a cache, but the property is actually called Quota on this call.

**Comment by brenankeller** [comment]
This was resolved in the latest release.
