### ISSUE TITLE
Code Snippet Issue on #post-show-completes-per-day

### ISSUE THREAD

**Issue by nikheintzen** [lucidhq/developer-documentation#130]
I think the code snippets on this call are wrong: http://developer.lucidhq.com/?shell#post-show-completes-per-day

The payload is specifying "completes per day" when this call is actually giving you this info. The payload should be more like:

`{
   "CountryLanguageID": 9,
   "LengthOfInterview": 1,
   "Incidence": 100,
   "Price": 5,
   "Quotas": [
      {
         "Conditions": [
            {
               "QuestionID": 42,
               "PreCodes": [
                  "18",
                  "19",
                  "20",
                  "21",
                  "22",
                  "23",
                  "24",
                  "25",
                  "26",
                  "27",
                  "28",
                  "29"
               ]
            },
            {
               "QuestionID": 43,
               "PreCodes": [
                  "1"
               ]
            }
         ]
      }
   ]
}`

**Comment by brenankeller** [comment]
I believe this was resolved with #153
