### ISSUE TITLE
Broken link to http://knowledge.fulcrumexchange.com/?p=625

### ISSUE THREAD

**Issue by candrews** [lucidhq/developer-documentation#143]
In https://github.com/lucidhq/developer-documentation/blob/456be83f05230fa468eb3ecd61e831a545a1a5be/source/includes/guides/_demand.md :

> To streamline the user experience, you should also [include all qualifications on the survey entry link](http://knowledge.fulcrumexchange.com/?p=625). This should reduce the length of interview and improve conversion, further improving pricing.

http://knowledge.fulcrumexchange.com/?p=625 (the link href) gives "Server not found"

**Comment by nikheintzen** [comment]
Just checked and this issue has been fixed.
