### ISSUE TITLE
DELETE calls are inconsistent

### ISSUE THREAD

**Issue by ericslone** [lucidhq/developer-documentation#174]
DELETE calls vary widely; some are .post, others .get, and some are .delete.

**Comment by jusoskina** [comment]
This seems like an actual API issue rather than an issue with the docs. Or do you mean the delete calls are documented inconsistently? (I couldn't find an example of this in the code snippets, but will look closer if that is the case)

**Comment by ericslone** [comment]
I haven't looked at other examples but there are a few discrepancies for python. For example http://developer.lucidhq.com/#delete-remove-from-a-survey-group uses a post method in the code, http://developer.lucidhq.com/#delete-delete-a-link uses get, and http://developer.lucidhq.com/#delete-delete-an-allocation uses delete.
