### ISSUE TITLE
Add 429 HTTP Response Code

### ISSUE THREAD

**Issue by snchildress** [lucidhq/developer-documentation#214]
Hey let's add this response code in our HTTP responses table:

429 with a response:
`{"message":"API rate limit exceeded"}`

**Comment by wkuckro** [comment]
`We do not currently rate limit calls because we believe that would only limit your potential to innovate.` you'll need to fix this line too then in https://github.com/lucidhq/developer-documentation/blob/develop/source/includes/introduction/_introduction.md

**Comment by nikheintzen** [comment]
https://github.com/lucidhq/developer-documentation/pull/243
https://github.com/lucidhq/developer-documentation/pull/244

Pull requests to add 429 response code and updated the verbiage around rate limiting.
