### ISSUE TITLE
"CompletesPerDay" vs "Completes"

### ISSUE THREAD

**Issue by wkuckro** [lucidhq/developer-documentation#235]
We display "CompletesPerDay" when the argument we accept on feasibility is "Completes"

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L258

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L275

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L292

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L305

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L331

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L349

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L393

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L428

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L485

https://github.com/lucidhq/developer-documentation/blame/develop/source/includes/demand/_feasibility.md#L656

**Comment by nikheintzen** [comment]
Will,

Pull request for this update. Let me know if there's anything else on this one.

https://github.com/lucidhq/developer-documentation/pull/241
